### PR TITLE
Add Cursor Tags

### PR DESCRIPTION
**Pull request by Daniel-176**

### CODE REVIEW

**Comment by Daniel-176** [comment]
image

**Comment by Daniel-176** [comment]
image
tag is now before name

**Comment by Daniel-176** [comment]
Done(maybe)

**Comment by lithiumjs** [comment]
Maybe contain the tags within the username section (like the usernames on top of the page), and not right next to it?

**Comment by Daniel-176** [comment]
i can do it prob at December, 29

**Comment by Daniel-176** [comment]
it's now done, i think

**Comment by fucksophie** [comment]
Thanks for your contribution!

**Pull request merged**
